program HelpStore;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  Forms,
  Windows,
  Main in 'Main.pas' {FrmMain},
  Cadastros_DM in 'Cadastros_DM.pas' {DMCadastros: TDataModule},
  Application_DM in 'Application_DM.pas' {DmApp: TDataModule},
  Listagens_DM in 'Listagens_DM.pas' {DMListagens: TDataModule},
  Funcoes in 'Funcoes.pas',
  Localizar_Form in 'Localizar_Form.pas' {FrmLocalizar},
  Procedures_DM in 'Procedures_DM.pas' {DMProcs: TDataModule},
  Usuarios_DM in 'Usuarios_DM.pas' {DMUsuarios: TDataModule},
  Identificacao_Form in 'Identificacao_Form.pas' {FrmIdent},
  OpUsuario_Form in 'OpUsuario_Form.pas' {FrmOpUsuario},
  PessoasFJ_Form in 'PessoasFJ_Form.pas' {FrmPessoasFJ},
  Logradouros_Form in 'Logradouros_Form.pas' {FrmLogradouros},
  Funcionarios_Form in 'Funcionarios_Form.pas' {FrmFuncionarios},
  Filtrar_Form in 'Filtrar_Form.pas' {FrmFiltrar},
  Atividades_Form in 'Atividades_Form.pas' {FrmAtividades},
  Marcas_Form in 'Marcas_Form.pas' {FrmMarcas},
  Unidades_Form in 'Unidades_Form.pas' {FrmUnidades},
  Reducoes_Form in 'Reducoes_Form.pas' {FrmReducoes},
  Tipo_Documento_Form in 'Tipo_Documento_Form.pas' {FrmTipoDoctos},
  Centro_Custo_Form in 'Centro_Custo_Form.pas' {FrmCCusto},
  Aplicacoes_Form in 'Aplicacoes_Form.pas' {FrmAplicacoes},
  Entradas_Form in 'Entradas_Form.pas' {FrmEntradas},
  Empresas_DM in 'Empresas_DM.pas' {DMEmpresas: TDataModule},
  SelEmpresa_Form in 'SelEmpresa_Form.pas' {FrmSelEmpresa},
  Receber_Form in 'Receber_Form.pas' {FrmReceber},
  EntraString_Form in 'EntraString_Form.pas' {FrmEntraString},
  ConsultaReceber_Form in 'ConsultaReceber_Form.pas' {FrmConsultaReceber},
  Localizar_Fornecedor in 'Localizar_Fornecedor.pas' {Frm_Localizar_Fornecedor},
  Dados_Baixa_Parcial_Form in 'Dados_Baixa_Parcial_Form.pas' {FrmDadosBaixaParcial},
  Fornecedores_Form in 'Fornecedores_Form.pas' {FrmFornecedores},
  Extorna_Receber_Form in 'Extorna_Receber_Form.pas' {FrmExtornaReceber},
  PerguntasPdv in 'PerguntasPdv.pas' {FormPerguntaPdv},
  Calculadora_Form in 'Calculadora_Form.pas' {FrmCalculadora},
  Entradas_DM in 'Entradas_DM.pas' {DMEntradas: TDataModule},
  Dados_Baixa_Form in 'Dados_Baixa_Form.pas' {FrmDadosBaixa},
  EntradasItens_Form in 'EntradasItens_Form.pas' {FrmEntradasItens},
  Filtra_Receber_Form in 'Filtra_Receber_Form.pas' {FrmFiltraContasReceber},
  Filtra_Receber_Previsao_Form in 'Filtra_Receber_Previsao_Form.pas' {FrmFiltraReceberPrevisao},
  Pagar_Form in 'Pagar_Form.pas' {FrmPagar},
  Extorna_Pagar_Form in 'Extorna_Pagar_Form.pas' {FrmExtornaPagar},
  Baixa_Pagar_Multiplos_Form in 'Baixa_Pagar_Multiplos_Form.pas' {FrmBaixaPagarSelecao},
  Dados_Baixa_Pagar_Multiplos_Form in 'Dados_Baixa_Pagar_Multiplos_Form.pas' {FrmDadosBaixaPagarSelecao},
  EntradasFat_Form in 'EntradasFat_Form.pas' {FrmEntradasFat},
  Plano_DM in 'Plano_DM.pas' {DmPlano: TDataModule},
  Plano_Form in 'Plano_Form.pas' {FrmPlano},
  Movimento_Contabil_Form in 'Movimento_Contabil_Form.pas' {FrmMov_Contabil},
  Localizar_Conta in 'Localizar_Conta.pas' {Frm_Localizar_Conta},
  Movimento_Form in 'Movimento_Form.pas' {FrmMovimento},
  Bancos_Form in 'Bancos_Form.pas' {FrmBancos},
  Entra_Periodo_Banco_Form in 'Entra_Periodo_Banco_Form.pas' {frmRelExtratoBancario},
  Localizar_ContaCod in 'Localizar_ContaCod.pas' {Frm_Localizar_ContaCod},
  Vendas_Dm in 'Vendas_Dm.pas' {DmVendas: TDataModule},
  Vendas_Form in 'Vendas_Form.pas' {FrmVendas},
  SelEntradas_Form in 'SelEntradas_Form.pas' {FrmSelEntradas},
  SelVendas_Form in 'SelVendas_Form.pas' {FrmSelVendas},
  VendasItens_Form in 'VendasItens_Form.pas' {FrmVendasItens},
  LocalizarProd_Form in 'LocalizarProd_Form.pas' {FrmLocalizarProd},
  Estoque_Dm in 'Estoque_Dm.pas' {DmEstoque: TDataModule},
  LocalizarProd_DM in 'LocalizarProd_DM.pas' {DMLocalizarProd: TDataModule},
  Seguranca_DM in 'Seguranca_DM.pas' {DMSeguranca: TDataModule},
  ConfDir_Form in 'ConfDir_Form.pas' {FrmConfDir},
  SelFaturaVendas_Form in 'SelFaturaVendas_Form.pas' {FrmSelFaturaVendas},
  Caixas_Form in 'Caixas_Form.pas' {FrmCaixas},
  FaturaCupom_Form in 'FaturaCupom_Form.pas' {FrmFaturaCupom},
  Pendencias_Form in 'Pendencias_Form.pas' {FrmPendencias},
  VerificaLimiteCredito_Form in 'VerificaLimiteCredito_Form.pas' {FrmLimitesCreditos},
  MensagemFaturamento_Form in 'MensagemFaturamento_Form.pas' {FrmMensagemFaturamento},
  VendasPdv_Form in 'VendasPdv_Form.pas' {FrmVendasPdv},
  VendasPdvItens_Form in 'VendasPdvItens_Form.pas' {FrmVendasPdvItens},
  SelVendasPdv_Form in 'SelVendasPdv_Form.pas' {FrmSelVendasPdv},
  Clientes_Form in 'Clientes_Form.pas' {FrmClientes},
  Caixa_Dm in 'Caixa_Dm.pas' {DmCaixa: TDataModule},
  Usuarios_Form in 'Usuarios_Form.pas' {FrmUsuarios},
  Kardex_FRel in 'Kardex_FRel.pas' {FRelKardex},
  Relatorios_DM in 'Relatorios_DM.pas' {DMRelatorios: TDataModule},
  ConsultaVendas_Form in 'ConsultaVendas_Form.pas' {FrmConsultaVenda},
  Cheque_Venda_Form in 'Cheque_Venda_Form.pas' {FrmCheque_Venda},
  Seleciona_Caixas_Form in 'Seleciona_Caixas_Form.pas' {FrmSelecionaCaixas},
  Orcamentos_Form in 'Orcamentos_Form.pas' {FrmOrcamentos},
  OrcamentosItens_Form in 'OrcamentosItens_Form.pas' {FrmOrcamentosItens},
  ListaPrecos_FRel in 'ListaPrecos_FRel.pas' {FRelListaPrecos},
  ListaPrecosAZ_FRel in 'ListaPrecosAZ_FRel.pas' {FRelListaPrecosAZ},
  ListaSimp_FRel in 'ListaSimp_FRel.pas' {FRelListaSimp},
  FisicaFin_FRel in 'FisicaFin_FRel.pas' {FRelFisicaFin},
  Pdv_DM in 'Pdv_DM.pas' {DmPdv: TDataModule},
  Pdv_Frm in 'Pdv_Frm.pas' {FrmPdv},
  comsetup_Form in 'comsetup_Form.pas' {frmSetup},
  FaturaVenda_Form in 'FaturaVenda_Form.pas' {FrmFaturaVenda},
  EnviaCaixa_FRel in 'EnviaCaixa_FRel.pas' {FRelEnviaCaixa},
  NaturezaOper_Form in 'NaturezaOper_Form.pas' {FrmNaturezaOper},
  Terceiros_Form in 'Terceiros_Form.pas' {FrmTerceiros},
  CotasSB_Form in 'CotasSB_Form.pas' {FrmCotasSB},
  Motoristas_Form in 'Motoristas_Form.pas' {FrmMotoristas},
  Veiculos_Form in 'Veiculos_Form.pas' {FrmVeiculos},
  TrocoPdv_Form in 'TrocoPdv_Form.pas' {FrmTroco},
  MontaCargas_Form in 'MontaCargas_Form.pas' {FrmMontaCargas},
  QuantidadePdv_Form in 'QuantidadePdv_Form.pas' {FrmQuantidadePdv},
  AcrDescPdv_Form in 'AcrDescPdv_Form.pas' {FrmAcrescimoDescontoPdv},
  Grupos_Form in 'Grupos_Form.pas' {FrmGrupos},
  ConveniadoPdv_Form in 'ConveniadoPdv_Form.pas' {FrmConveniadoPdv},
  UnitarioPdv_Form in 'UnitarioPdv_Form.pas' {FrmUnitarioPdv},
  LocalizarClientePdv in 'LocalizarClientePdv.pas' {FrmLocalizarClientePdv},
  EntraDataPdv_Form in 'EntraDataPdv_Form.pas' {FrmEntraPeriodoPdv},
  EntraNumeroInteiro_Form in 'EntraNumeroInteiro_Form.pas' {FrmEntraNumeroInteiro},
  Saidas_FRel in 'Saidas_FRel.pas' {FRelSaidas},
  ConsultaProdPdv_Form in 'ConsultaProdPdv_Form.pas' {FrmConsultaProdPdv},
  SenhaGerencialPdv_Form in 'SenhaGerencialPdv_Form.pas' {FrmSenhaGerencial},
  TipoFaturaVenda_Form in 'TipoFaturaVenda_Form.pas' {FrmTipoFaturaVenda},
  Series_Form in 'Series_Form.pas' {FrmSeries},
  ClientesAlf_FRel in 'ClientesAlf_FRel.pas' {FRelClientesAlf},
  FornecedoresAlf_FRel in 'FornecedoresAlf_FRel.pas' {FRelFornecedoresAlf},
  FornecedoresRes_FRel in 'FornecedoresRes_FRel.pas' {FRelFornecedoresRes},
  FecharCaixa_Form in 'FecharCaixa_Form.pas' {FrmFecharCaixas},
  Localizar_Natureza in 'Localizar_Natureza.pas' {Frm_Localizar_Natureza},
  Localizar_Terceiro in 'Localizar_Terceiro.pas' {Frm_Localizar_Terceiros},
  Cargas_Form in 'Cargas_Form.pas' {FrmCargas},
  Localizar_Vendas in 'Localizar_Vendas.pas' {FrmLocVendas},
  EntraNumeroReal_Form in 'EntraNumeroReal_Form.pas' {FrmEntraNumeroReal},
  Classificacoes_Form in 'Classificacoes_Form.pas' {FrmClassificacoes},
  MensagemClassificacao_Form in 'MensagemClassificacao_Form.pas' {FrmMensagemClassificacao},
  ProdutosFor_FRel in 'ProdutosFor_FRel.pas' {FRelProdutosFor},
  Localizar_Cliente in 'Localizar_Cliente.pas' {Frm_Localizar_Cliente},
  LocalizarAplicacoes_Form in 'LocalizarAplicacoes_Form.pas' {FrmLocalizarAplicacao},
  Localizar_Orcamentos in 'Localizar_Orcamentos.pas' {FrmLocOrcamentos},
  EntraNumeroOrcamento_Form in 'EntraNumeroOrcamento_Form.pas' {FrmEntraNumeroOrcamento},
  ConfEtiquetas_Form in 'ConfEtiquetas_Form.pas' {FrmConfEtiquetas},
  EntraSenha_Form in 'EntraSenha_Form.pas' {FrmEntraSenha},
  EntraDescontoVenda_Form in 'EntraDescontoVenda_Form.pas' {FrmEntraDesconto},
  Configuraboleto_Form in 'Configuraboleto_Form.pas' {FrmConfigurarBoletos},
  ClientesRes_FRel in 'ClientesRes_FRel.pas' {FRelClientesRes},
  Mensagem_DM in 'Mensagem_DM.pas' {DMMensagem: TDataModule},
  VendasPeriodo_FRel in 'VendasPeriodo_FRel.pas' {FRelVendasPeriodo},
  Mensagem_Form in 'Mensagem_Form.pas' {FrmMensagem},
  GraficoVendasGrupoProdutos_Form in 'GraficoVendasGrupoProdutos_Form.pas' {FrmGraficoVendasPorGrupo},
  ConsultaVendasVendedor_Form in 'ConsultaVendasVendedor_Form.pas' {FrmConsultaVendasVend},
  VendasVendedor_FRel in 'VendasVendedor_FRel.pas' {FRelVendasVendedor},
  GraficoVendas_Form in 'GraficoVendas_Form.pas' {FrmGraficoVendas},
  AuxContagem_FRel in 'AuxContagem_FRel.pas' {FRelAuxContagemEstoque},
  CaixaSaidas_Form in 'CaixaSaidas_Form.pas' {FrmCaixaSaidas},
  Localizar_Propriedade in 'Localizar_Propriedade.pas' {Frm_Localizar_Propriedade},
  Produtos_Aplicaoes_Form in 'Produtos_Aplicaoes_Form.pas' {FrmProdutos_Aplicacoes},
  Tipo_Veiculos_Form in 'Tipo_Veiculos_Form.pas' {FrmTipo_Veiculos},
  Marca_Veiculos_Form in 'Marca_Veiculos_Form.pas' {FrmMarcas_Veiculos},
  ConfiguraDuplicata_Form in 'ConfiguraDuplicata_Form.pas' {FrmConfigurarDuplicatas},
  ArredondaTruncaPdv_Form in 'ArredondaTruncaPdv_Form.pas' {FrmArredondaTruncaPdv},
  ConsultaConveniados_Form in 'ConsultaConveniados_Form.pas' {FrmConsultaConvenio},
  ConfirmaExtorno_Form in 'ConfirmaExtorno_Form.pas' {FrmConfirmaExtorno},
  Cotacoes_Form in 'Cotacoes_Form.pas' {FrmCotacoes},
  CotacoesItens_Form in 'CotacoesItens_Form.pas' {FrmCotacoesItens},
  SelCotacoes_Form in 'SelCotacoes_Form.pas' {FrmSelCotacoes},
  Cotacao_FRel in 'Cotacao_FRel.pas' {FRelImprimeCotacao},
  ConfiguradorBackup_Frm in 'ConfiguradorBackup_Frm.pas' {FrmConfiguradorBck},
  AlteraVendas_Form in 'AlteraVendas_Form.pas' {FrmAlteraVendas},
  Procedures2_DM in 'Procedures2_DM.pas' {DMProcs2: TDataModule},
  ContasPessoas_Form in 'ContasPessoas_Form.pas' {FrmContasPessoas},
  ClientesCategoria_Form in 'ClientesCategoria_Form.pas' {FrmClientesCategoria},
  MensagemDisPlay_Form in 'MensagemDisPlay_Form.pas' {FrmMensagemDisplay},
  Administradoras_Form in 'Administradoras_Form.pas' {FrmAdministradoras},
  Cartao_Venda_Form in 'Cartao_Venda_Form.pas' {FrmCartao_Venda},
  Lotes_Form in 'Lotes_Form.pas' {FrmLotes},
  Cheque_Manual_Form in 'Cheque_Manual_Form.pas' {FrmCheque_Pre},
  Rel_Pagas_Centro_Form in 'Rel_Pagas_Centro_Form.pas' {FrmFiltraContasPagasCentro},
  Cheques_FRel in 'Cheques_FRel.pas' {FRelCheque},
  Moedas_Form in 'Moedas_Form.pas' {FrmMoedas},
  DigitaCotacoes_Form in 'DigitaCotacoes_Form.pas' {FrmDigitaCotacoes},
  Localizar_Veiculos in 'Localizar_Veiculos.pas' {Frm_Localizar_Veiculos},
  ConfiguraNotaPromissoria_Form in 'ConfiguraNotaPromissoria_Form.pas' {FrmConfigurarNotaPromissoria},
  NotaPromissoria_FRel in 'NotaPromissoria_FRel.pas' {FrmImprimePromissoria},
  Baixa_Receber_Convenio_Form in 'Baixa_Receber_Convenio_Form.pas' {FrmBaixaReceberConvenio},
  EntraComplementoNf_Form in 'EntraComplementoNf_Form.pas' {FrmEntraComplementoNf},
  Dados_Desconto_Form in 'Dados_Desconto_Form.pas' {FrmDadosDesconto},
  Tipo_Impressora_Form in 'Tipo_Impressora_Form.pas' {FrmTipoImpressora},
  Inclui_Nota_Fatura_Form in 'Inclui_Nota_Fatura_Form.pas' {FrmIncluirNotaFatura},
  EtiquetasTinta_FRel in 'EtiquetasTinta_FRel.pas' {FRelEtiquetasTinta},
  PosicaoEstoqueContagem_FRel in 'PosicaoEstoqueContagem_FRel.pas' {FRelPosicaoEstoqueContagem},
  Entra_Dados_Consumidor_Form in 'Entra_Dados_Consumidor_Form.pas' {FrmEntraDadosConsumidor},
  Cidades_Form in 'Cidades_Form.pas' {FrmCidades},
  Dados_Baixa_Loja_Form in 'Dados_Baixa_Loja_Form.pas' {FrmDadosBaixaLoja},
  VendasMaioresCliente_FRel in 'VendasMaioresCliente_FRel.pas' {FRelVendasMaioresCliente},
  Cheque_Ctb_Form in 'Cheque_Ctb_Form.pas' {FrmCheques_Ctb},
  Filtra_Cheques_Form in 'Filtra_Cheques_Form.pas' {Filtra_Cheques_Frm},
  ImpCheques_Form in 'ImpCheques_Form.pas' {FrmImpressaoChq},
  Motivos_Devolucao_Form in 'Motivos_Devolucao_Form.pas' {FrmMotivos_Devolucao},
  SelFin_Cheques_Form in 'SelFin_Cheques_Form.pas' {FrmSelFinCheques},
  Dados_Devolucao_Form in 'Dados_Devolucao_Form.pas' {FrmDadosDevolucao},
  Dados_Acerto_Form in 'Dados_Acerto_Form.pas' {FrmDadosAcertoCheque},
  ConfirmaTroco_Form in 'ConfirmaTroco_Form.pas' {FrmConfirmaTroco},
  Transportadoras_Form in 'Transportadoras_Form.pas' {FrmTransportadoras},
  Localizar_Transportadora in 'Localizar_Transportadora.pas' {Frm_Localizar_Transportadoras},
  SelTrocas_Form in 'SelTrocas_Form.pas' {FrmSelTrocas},
  Trocas_Form in 'Trocas_Form.pas' {FrmTrocas},
  TrocasItens_Form in 'TrocasItens_Form.pas' {FrmTrocasItens},
  EnviaTrocaCaixa_FRel in 'EnviaTrocaCaixa_FRel.pas' {FRelEnviaTrocaCaixa},
  CotasVendedor_FRel in 'CotasVendedor_FRel.pas' {FRelCotasVendedor},
  Servicos_DM in 'Servicos_DM.pas' {DmServicos: TDataModule},
  Servicos_Form in 'Servicos_Form.pas' {FrmServicos},
  Motores_Form in 'Motores_Form.pas' {FrmMotores},
  Localizar_Servicos in 'Localizar_Servicos.pas' {Frm_Localizar_Servico},
  Mecanicos_Form in 'Mecanicos_Form.pas' {FrmMecanicos},
  Ordens_Servicos_Form in 'Ordens_Servicos_Form.pas' {FrmOrdens_Servicos},
  SelOrdens_Form in 'SelOrdens_Form.pas' {FrmSelOrdens},
  PosicaoEstoqueContagemSub_FRel in 'PosicaoEstoqueContagemSub_FRel.pas' {FRelPosicaoEstoqueContagemSub},
  Cria_Tab_Ext_Prod_Form in 'Cria_Tab_Ext_Prod_Form.pas' {FrmTabelaExterna},
  EtiquetasTintaMesa_FRel in 'EtiquetasTintaMesa_FRel.pas' {FRelEtiquetasTintaMesa},
  Produtos_Form in 'Produtos_Form.pas' {FrmProdutos},
  ProdutosAliquota_FRel in 'ProdutosAliquota_FRel.pas' {FRelProdutosAliq},
  Entra_Valor_Form in 'Entra_Valor_Form.pas' {FrmEntraValor},
  FaturaTroca_Form in 'FaturaTroca_Form.pas' {FrmFaturaTroca},
  ClientesConv_FRel in 'ClientesConv_FRel.pas' {FRelClientesConv},
  Migrar_Dados_Form in 'Migrar_Dados_Form.pas' {FrmMigraDados},
  Vendasgrupo_FRel in 'Vendasgrupo_FRel.pas' {FRelVendasGrupos},
  Propriedades_Form in 'Propriedades_Form.pas' {FrmPropriedades},
  VendasAnalitico_FRel in 'VendasAnalitico_FRel.pas' {FRelVendasAnalitico},
  Procedures3_DM in 'Procedures3_DM.pas' {DMProcs3: TDataModule},
  EnviaCaixaCusto_FRel in 'EnviaCaixaCusto_FRel.pas' {FRelEnviaCaixaOrcamento},
  Localizar_Mecanico in 'Localizar_Mecanico.pas' {Frm_Localizar_Mecanicos},
  Localizar_Viajante in 'Localizar_Viajante.pas' {Frm_Localizar_Viajante},
  Localizar_Motor in 'Localizar_Motor.pas' {Frm_Localizar_Motor},
  EntraDescricao_Form in 'EntraDescricao_Form.pas' {FrmEntraDescricao},
  SelVendasCanceladas_Form in 'SelVendasCanceladas_Form.pas' {FrmSelVendasCanceladas},
  VendasCanceladas_FRel in 'VendasCanceladas_FRel.pas' {FRelVendasCanceladas},
  ConveniadoCheque_Form in 'ConveniadoCheque_Form.pas' {FrmConveniadoCheque},
  BxReceberAlf_FRel in 'BxReceberAlf_FRel.pas' {FRelRecebidasAlfabetico},
  ConsultaVendasIndicados_Form in 'ConsultaVendasIndicados_Form.pas' {FrmConsultaVendasIndicados},
  Extorna_Caixa_Form in 'Extorna_Caixa_Form.pas' {FrmExtornaCaixa},
  ConsultaFatura_Pagas_Form in 'ConsultaFatura_Pagas_Form.pas' {FrmConsultaFaturasPagas},
  GraficoAcompanhamento_Vendas_Form in 'GraficoAcompanhamento_Vendas_Form.pas' {FrmAcompanhamentoVendas},
  VendasAcompanhamento_FRel in 'VendasAcompanhamento_FRel.pas' {FRelVendasAcompanhamento},
  Captura_Cheque_Form in 'Captura_Cheque_Form.pas' {FrmCapturaCheque},
  ClientesCheque_FRel in 'ClientesCheque_FRel.pas' {FRelClienteCheque},
  Entra_Data_Cheque_Form in 'Entra_Data_Cheque_Form.pas' {FrmEntraDataCheque},
  ControleQualidade_Form in 'ControleQualidade_Form.pas' {FrmCtrlQualidade},
  Localizar_Ordens in 'Localizar_Ordens.pas' {FrmLocOrdens},
  Baixa_Receber_Multiplos_Parc_Form in 'Baixa_Receber_Multiplos_Parc_Form.pas' {FrmBaixaReceberSelecaoParc},
  Consulta_Pessoas_Form in 'Consulta_Pessoas_Form.pas' {FrmMalaDireta},
  QrepCondiconal_Form in 'QrepCondiconal_Form.pas' {QrepCondicional: TQuickRep},
  PagasAlf_FRel in 'PagasAlf_FRel.pas' {FRelPagasAlfabetico},
  EntraCentro_Form in 'EntraCentro_Form.pas' {FrmEntraCentro},
  TrocasCliente_FRel in 'TrocasCliente_FRel.pas' {FRelTrocasCliente},
  NotaPromissoriaTroca_FRel in 'NotaPromissoriaTroca_FRel.pas' {FrmImprimePromissoriaTroca},
  Lancar_Pagas_Form in 'Lancar_Pagas_Form.pas' {FrmLancContaPaga},
  VendasMarca_FRel in 'VendasMarca_FRel.pas' {FRelVendasMarcas},
  ConfiguraPerfil_Form in 'ConfiguraPerfil_Form.pas' {FrmConfigurarPerfil},
  Ctb_Altera_Movimentos_Form in 'Ctb_Altera_Movimentos_Form.pas' {FrmCtb_Altera_Movtos},
  MotivosCobranca_Form in 'MotivosCobranca_Form.pas' {FrmMotivosCobranca},
  Agendamento_Cobranca_Form in 'Agendamento_Cobranca_Form.pas' {FrmAgendamentoCobranca},
  ListagemCobrancas_Form in 'ListagemCobrancas_Form.pas' {FrmListagemCobranca},
  AberturaCaixas_Form in 'AberturaCaixas_Form.pas' {FrmAberturaCaixas},
  Ver_Agendamentos_Cobranca_Form in 'Ver_Agendamentos_Cobranca_Form.pas' {FrmVerAgendamentoCobranca},
  Cor_Form in 'Cor_Form.pas' {FrmCores},
  Material_Form in 'Material_Form.pas' {FrmMateriais},
  Grades_Form in 'Grades_Form.pas' {FrmGrades},
  PrecosEspeciaisPessoas_Form in 'PrecosEspeciaisPessoas_Form.pas' {FrmPrecosEspeciais},
  Ctb_Conf_Rel_Form in 'Ctb_Conf_Rel_Form.pas' {FrmCtbConfRel},
  Cobrador_Form in 'Cobrador_Form.pas' {FrmCobrador},
  Ctb_Configuracoes_Form in 'Ctb_Configuracoes_Form.pas' {FrmCfgCtb},
  AnaliseCustos_Form in 'AnaliseCustos_Form.pas' {FrmAnaliseCustos},
  ConsultaCobrancas_Pessoa_Form in 'ConsultaCobrancas_Pessoa_Form.pas' {FrmManutencaoCobrancaPessoa},
  Perfil_Grades_Form in 'Perfil_Grades_Form.pas' {FrmPerfil_Grades},
  Localizar_Grade in 'Localizar_Grade.pas' {Frm_Localizar_Grades},
  Promocoes_Form in 'Promocoes_Form.pas' {FrmPromocao},
  Entra_Dados_receber_Pdv_Form in 'Entra_Dados_receber_Pdv_Form.pas' {FrmEntraDados_Receber_Pdv},
  Historico_DM in 'Historico_DM.pas' {DMHistorico: TDataModule},
  Historico_Form in 'Historico_Form.pas' {FrmHistorico},
  Comissoes_Clientes_Form in 'Comissoes_Clientes_Form.pas' {FrmComissaoCliente},
  Localizar_Garantias in 'Localizar_Garantias.pas' {Frm_Localizar_Garantias},
  Garantia_FRel in 'Garantia_FRel.pas' {FRelGarantia},
  Vendedor_Caixa_Form in 'Vendedor_Caixa_Form.pas' {FrmVendedor_Caixa},
  Vendas_Cor_Form in 'Vendas_Cor_Form.pas' {FrmVendas_Cor},
  ChequesDevolvidos_FRel in 'ChequesDevolvidos_FRel.pas' {FRelChequeDevolvido},
  EntraNumeroFatura_Form in 'EntraNumeroFatura_Form.pas' {FrmEntraNumeroFatura},
  Localizar_Faturas in 'Localizar_Faturas.pas' {FrmLocFaturas},
  Fatura_Parcelas_Form in 'Fatura_Parcelas_Form.pas' {FrmFatura_Parcelas},
  CaixaResumoMovimentos_Form in 'CaixaResumoMovimentos_Form.pas' {FrmCaixaResumoMovtos},
  Ordens_Servicos_movtos_Form in 'Ordens_Servicos_movtos_Form.pas' {FrmOrdens_Servicos_Movtos},
  Transfere_Cadastros_Form in 'Transfere_Cadastros_Form.pas' {FrmTransfereCadastros},
  Ordens_Servicos_Itens_Form in 'Ordens_Servicos_Itens_Form.pas' {FrmOrdens_Servicos_Itens},
  Ordens_Servicos_Itens_Valores_Form in 'Ordens_Servicos_Itens_Valores_Form.pas' {FrmEntraValorOs_Itens},
  Cartao_Reemb_FRel in 'Cartao_Reemb_FRel.pas' {FRelCartaoReemb},
  BxReceberAlfFat_FRel in 'BxReceberAlfFat_FRel.pas' {FRelRecebidasAlfabeticoFat},
  Entra_Dados_Movtos_Pdv_Form in 'Entra_Dados_Movtos_Pdv_Form.pas' {FrmEntraDados_Movtos_Pdv},
  Cartao_Manual_Form in 'Cartao_Manual_Form.pas' {FrmMovto_Cartao},
  Filtra_Cartao_Form in 'Filtra_Cartao_Form.pas' {FrmFiltra_Cartao},
  Migrar_Dados_Toledo_Form in 'Migrar_Dados_Toledo_Form.pas' {FrmMigraDadosToledo},
  Entra_Conciliacao_Cartao_Form in 'Entra_Conciliacao_Cartao_Form.pas' {FrmConciliacaoCartao},
  Procedures4_DM in 'Procedures4_DM.pas' {DMProcs4: TDataModule},
  Ordens_Servicos_Itens_Orc_Form in 'Ordens_Servicos_Itens_Orc_Form.pas' {FrmOrdens_Servicos_Itens_Orc},
  Ordens_Servicos_Itens_Valores_Orc_Form in 'Ordens_Servicos_Itens_Valores_Orc_Form.pas' {FrmEntraValorOs_Itens_Orc},
  Localizar_Orcamentos_Ordem in 'Localizar_Orcamentos_Ordem.pas' {FrmLocOrcamentos_Ordem},
  EntraNumeroOrcamento_Ordem_Form in 'EntraNumeroOrcamento_Ordem_Form.pas' {FrmEntraNumeroOrcamentoOrdem},
  Localizar_Convenio in 'Localizar_Convenio.pas' {Frm_Localizar_Convenios},
  Ver_Agendamentos_Cobranca_Periodo_Form in 'Ver_Agendamentos_Cobranca_Periodo_Form.pas' {FrmVerAgend_Cobr_Periodo},
  ChequesAcertados_FRel in 'ChequesAcertados_FRel.pas' {FRelChequesAcertados},
  Faturas_Agrupadas_Form in 'Faturas_Agrupadas_Form.pas' {FrmFaturas_Notas},
  ListaPrecosIndexada_FRel in 'ListaPrecosIndexada_FRel.pas' {FRelListaPrecosIndexada},
  Cartao_Manutencao_Form in 'Cartao_Manutencao_Form.pas' {FrmMamutencao_Cartao},
  Receber_Parcelamento_Form in 'Receber_Parcelamento_Form.pas' {FrmReceberParcelamento},
  SelGarantias_Form in 'SelGarantias_Form.pas' {FrmSelGarantias},
  Garantias_Form in 'Garantias_Form.pas' {FrmGarantias},
  GarantiasItens_Form in 'GarantiasItens_Form.pas' {FrmGarantiasItens},
  EnviaGarantiaCaixa_FRel in 'EnviaGarantiaCaixa_FRel.pas' {FRelEnviaGarantiaCaixa},
  Entra_Conciliacao_Cheque_Form in 'Entra_Conciliacao_Cheque_Form.pas' {FrmConciliacaoCheque},
  Entra_Dados_Autorizado_Form in 'Entra_Dados_Autorizado_Form.pas' {FrmEntraDadosAutorizado},
  EtiquetaProduto_Grade_Form in 'EtiquetaProduto_Grade_Form.pas' {FrmEtqProdutoGrade},
  Entradas_Grades_Form in 'Entradas_Grades_Form.pas' {FrmEntradas_Grades},
  Entra_Dados_Cheques_Form in 'Entra_Dados_Cheques_Form.pas' {FrmEntraDadosCheques},
  Filtra_Resumo_Comissoes_Form in 'Filtra_Resumo_Comissoes_Form.pas' {FrmFiltraResumoComissoes},
  PosicaoEstoque_Venda_FRel in 'PosicaoEstoque_Venda_FRel.pas' {FRelPosicaoEstoqueVenda},
  Migrar_Dados_Filizola_Form in 'Migrar_Dados_Filizola_Form.pas' {FrmMigraDadosFilizola},
  ConsultaPagasData_Form in 'ConsultaPagasData_Form.pas' {FrmFiltrarPagasData},
  BxReceberCobrador_FRel in 'BxReceberCobrador_FRel.pas' {FRelRecebidasCobrador},
  OrdensPeriodo_FRel in 'OrdensPeriodo_FRel.pas' {FRelHistoricoEquipamento},
  VendasAnalise_Cliente_FRel in 'VendasAnalise_Cliente_FRel.pas' {FRelVendasAnaliseCliente},
  ConsultaTrocas_Form in 'ConsultaTrocas_Form.pas' {FrmConsultaTroca},
  ComissoesVendedor_Rec_FRel in 'ComissoesVendedor_Rec_FRel.pas' {FRelComiVendRecebimento},
  Ordens_ServicosItens_Orc_Form in 'Ordens_ServicosItens_Orc_Form.pas' {FrmOrdensServicosItens_Orc},
  Grades_Entradas_Form in 'Grades_Entradas_Form.pas' {FrmGrades_Entradas},
  VendasSubgrupo_Trimestre_FRel in 'VendasSubgrupo_Trimestre_FRel.pas' {FRelVendasSubGruposTrimestre},
  Filtra_Fluxo_Caixa_Form in 'Filtra_Fluxo_Caixa_Form.pas' {Filtra_Fluxo_Caixas_Frm},
  Log_Transacoes_Form in 'Log_Transacoes_Form.pas' {FrmLog},
  Procedures5_DM in 'Procedures5_DM.pas' {DMProcs5: TDataModule},
  VendasGrupoSel_FRel in 'VendasGrupoSel_FRel.pas' {FRelVendasGruposSel},
  Ordens_ServicosItens_Form in 'Ordens_ServicosItens_Form.pas' {FrmOrdensServicosItens},
  VendasMarcaSel_FRel in 'VendasMarcaSel_FRel.pas' {FRelVendasMarcasSel},
  Local_Cobranca_Form in 'Local_Cobranca_Form.pas' {FrmLocais_Cobranca},
  Localizar_Generico in 'Localizar_Generico.pas' {Frm_Localizar_Generico},
  Localizar_Forma in 'Localizar_Forma.pas' {Frm_Localizar_FormaPagto},
  Localizar_Precos_Servicos in 'Localizar_Precos_Servicos.pas' {Frm_Lista_Precos_Servicos},
  Localizar_Lote in 'Localizar_Lote.pas' {Frm_Localizar_Lote},
  PosicaoEstoqueGrade_FRel in 'PosicaoEstoqueGrade_FRel.pas' {FRelPosicaoEstoqueGrade},
  Tipo_Contrato_Form in 'Tipo_Contrato_Form.pas' {FrmTipos_Contratos},
  Localizar_Propriedade_Ie in 'Localizar_Propriedade_Ie.pas' {Frm_Localizar_Propriedade_Ie},
  PosicaoEstoqueGrade_Marca_FRel in 'PosicaoEstoqueGrade_Marca_FRel.pas' {FRelPosicaoEstoqueGrade_Marca},
  Modelo_Propriedade_Form in 'Modelo_Propriedade_Form.pas' {FrmModelos_Propriedades},
  RecibosPagar in 'RecibosPagar.pas' {frmRecibosPagar},
  ContagemGrade_Form in 'ContagemGrade_Form.pas' {FrmContagemGrade},
  Produtos_Tribut_Revenda_Form in 'Produtos_Tribut_Revenda_Form.pas' {FrmProdutos_Tribut_Revenda},
  Rel_Vendas_Servicos_FRel in 'Rel_Vendas_Servicos_FRel.pas' {FRelVendasServicos},
  Localizar_Produto_Cadastro_Auto in 'Localizar_Produto_Cadastro_Auto.pas' {FrmLocProdutoCadastro_Auto},
  Entra_EstadoCheque_Form in 'Entra_EstadoCheque_Form.pas' {FrmEntraEstadoCheque},
  Localizar_Grade_Pdv in 'Localizar_Grade_Pdv.pas' {Frm_Localizar_Grades_Pdv},
  Cheque_Pdv_Form in 'Cheque_Pdv_Form.pas' {FrmCheque_Pdv},
  ChequesEstados_FRel in 'ChequesEstados_FRel.pas' {FRelChequeEstado},
  Ficha_Cliente_Inativos_FRel in 'Ficha_Cliente_Inativos_FRel.pas' {FRelFicha_Clientes_Inativos},
  ClientesInativos_FRel in 'ClientesInativos_FRel.pas' {FRelClientesInativos},
  VendasCidade_FRel in 'VendasCidade_FRel.pas' {FRelVendasCidade},
  Calculadora_Pdv_Form in 'Calculadora_Pdv_Form.pas' {FrmCalculadora_Pdv},
  Defeitos_Form in 'Defeitos_Form.pas' {FrmDefeitos},
  ConsultaConveniados_Baixas_Form in 'ConsultaConveniados_Baixas_Form.pas' {FrmFiltrarRecConvenioBaixa},
  Pdv_Terminal_Consulta in 'Pdv_Terminal_Consulta.pas' {Frm_Pdv_Terminal_Consulta},
  Entradas_NaoRepostas_FRel in 'Entradas_NaoRepostas_FRel.pas' {FRelEntradasNaoRepostas},
  ProdutosNao_Repostos_FRel in 'ProdutosNao_Repostos_FRel.pas' {FRelProdutosNaoRepostos},
  Entradas_FRel in 'Entradas_FRel.pas' {FRelEntradas},
  Empresas_Form in 'Empresas_Form.pas' {FrmEmpresas},
  VeiculosPessoas_Form in 'VeiculosPessoas_Form.pas' {FrmVeiculosFrota},
  Remessa_FRel in 'Remessa_FRel.pas' {FRemessa},
  CaixaGeral_FRel in 'CaixaGeral_FRel.pas' {FRelListaCaixaGeral},
  Retorno_FRel in 'Retorno_FRel.pas' {FRetorno},
  Devolucoes_FRel in 'Devolucoes_FRel.pas' {FRelDevolucoes},
  VendasProdutos_FRel in 'VendasProdutos_FRel.pas' {FRelVendasProdutos},
  EntradasProdutos_FRel in 'EntradasProdutos_FRel.pas' {FRelEntradasProdutos},
  Ultimas_Vendas_Form in 'Ultimas_Vendas_Form.pas' {FrmUltimas_Vendas},
  Cotacoes_FRel in 'Cotacoes_FRel.pas' {FRelCotacoesPeriodo},
  ImprimeBoleto in 'ImprimeBoleto.pas' {frmImprimeBoleto},
  SetaNumPedidodv_Form in 'SetaNumPedidodv_Form.pas' {FrmSetaNumPedidoPdv},
  VendasClientesConsumidor_FRel in 'VendasClientesConsumidor_FRel.pas' {FRelVendasClientesConsumidor},
  VendasNatureza_FRel in 'VendasNatureza_FRel.pas' {FRelVendasNatureza},
  Financeiro_Dm in 'Financeiro_Dm.pas' {DmFinanceiro: TDataModule},
  Filtra_Clientes_Form in 'Filtra_Clientes_Form.pas' {FrmFiltraClientes},
  Mesas_Form in 'Mesas_Form.pas' {FrmMesas},
  Vendedores_Form in 'Vendedores_Form.pas' {FrmVendedores},
  Localizar_Vendedor_PDV in 'Localizar_Vendedor_PDV.pas' {Frm_Localizar_Vendedor},
  FuncoesPdv_Form in 'FuncoesPdv_Form.pas' {FrmFuncoesPdv},
  Help_Form in 'Help_Form.pas' {frmHelpPDV},
  Propriedades_FRel in 'Propriedades_FRel.pas' {FRelPropriedades},
  Filtra_Baixa_Form in 'Filtra_Baixa_Form.pas' {FrmBaixaContas},
  ListagemMod_Form in 'ListagemMod_Form.pas' {frmListagemMod},
  Cheque_Contabilidade in 'Cheque_Contabilidade.pas' {FrmCheque_Contabilidade},
  FormasPagto_Form in 'FormasPagto_Form.pas' {FrmFormasPagto},
  Splash_Form in 'Splash_Form.pas' {FrmSplash},
  Demonstrativo_Form in 'Demonstrativo_Form.pas' {frmDemonstrativo},
  Filtra_RelTerceiros_Form in 'Filtra_RelTerceiros_Form.pas' {frmRelTerceiros},
  Regioes_Form in 'Regioes_Form.pas' {FrmRegioes},
  EstoqueComprometido_FRel in 'EstoqueComprometido_FRel.pas' {FRelEstoqueComprometido},
  Financeiro_Dm2 in 'Financeiro_Dm2.pas' {dmFinanceiro2: TDataModule},
  Vendas_DM2 in 'Vendas_DM2.pas' {DmVendas2: TDataModule},
  ConsultaCobrancas_Form in 'ConsultaCobrancas_Form.pas' {FrmManutencaoCobranca},
  Filtra_Cobranca_Form in 'Filtra_Cobranca_Form.pas' {frmFiltraCobranca},
  Perfil_Pagto_Form in 'Perfil_Pagto_Form.pas' {FrmPerfilPagto},
  Perfil_Com_Form in 'Perfil_Com_Form.pas' {FrmPerfilComissao},
  ManutencaoComissoes_Form in 'ManutencaoComissoes_Form.pas' {FrmManutencaoComissao},
  Relatorios_DM2 in 'Relatorios_DM2.pas' {dmRelatorios2: TDataModule},
  ComissoesVendedor_FRel in 'ComissoesVendedor_FRel.pas' {FRelComissoesVendedor},
  Comissoes_FRel in 'Comissoes_FRel.pas' {FRelComissoesPendendes},
  Filtra_ManComissoes in 'Filtra_ManComissoes.pas' {frmFiltraManComissoes},
  Com_DadosReceber in 'Com_DadosReceber.pas' {frmComDadosReceber},
  Gera_PagarComissao in 'Gera_PagarComissao.pas' {frmGeraPagarComissao},
  Filtra_GeraComissao in 'Filtra_GeraComissao.pas' {frmFiltraGeraComissoes},
  Cheque_Financeiro_Form in 'Cheque_Financeiro_Form.pas' {FrmCheque_Planilha},
  Rel_GraficoVendasProd_Form in 'Rel_GraficoVendasProd_Form.pas' {Qrp2: TQuickRep},
  Sugestao_FRel in 'Sugestao_FRel.pas' {fRelSugestaoCompra},
  Receber_FRel2 in 'Receber_FRel2.pas' {fRelReceber2},
  Paises_Form in 'Paises_Form.pas' {FrmPaises},
  ListaFaturamento_Form in 'ListaFaturamento_Form.pas' {frmListaFaturamento},
  Cadastros_Dm2 in 'Cadastros_Dm2.pas' {dmCadastros2: TDataModule},
  StatusServico_Form in 'StatusServico_Form.pas' {frmStatusServico},
  TipoAtendimento_Form in 'TipoAtendimento_Form.pas' {FrmTipoAtendimento},
  MotivoChamado_Form in 'MotivoChamado_Form.pas' {frmMotivoChamado},
  Secoes_Produto_Form in 'Secoes_Produto_Form.pas' {FrmSecoes_Produtos},
  Entra_Periodo_Form in 'Entra_Periodo_Form.pas' {FrmEntraPeriodo},
  Filtra_Pagar_Form in 'Filtra_Pagar_Form.pas' {FrmFiltraContasPagar},
  Rel_Rechamados in 'Rel_Rechamados.pas' {FRel_Rechamados},
  Pagar_FRel2 in 'Pagar_FRel2.pas' {fRelPagar2},
  Equipamentos_FRel2 in 'Equipamentos_FRel2.pas' {fRelEquipamentos2},
  CarregarItens in 'CarregarItens.pas' {FrmCarregarItens},
  ConfirmarCarregamentoItens in 'ConfirmarCarregamentoItens.pas' {FrmConfirmarCarregamentoItens},
  SelCarga in 'SelCarga.pas' {FrmSelCarga},
  OrdemCarga_DM in 'OrdemCarga_DM.pas' {DmOrdemCarga: TDataModule},
  FichaCarga in 'FichaCarga.pas' {FrmFichaCarga},
  SeriesCustomizaveis in 'SeriesCustomizaveis.pas' {FrmSeriesCustomizaveis},
  SerieCustomizaveis_DM in 'SerieCustomizaveis_DM.pas' {DmSerie_Customizaveis: TDataModule},
  SelKardex in 'SelKardex.pas',
  EstoquePendencias in 'EstoquePendencias.pas' {FrmEstoquePendencia},
  Entradas_Lotes_Form in 'Entradas_Lotes_Form.pas' {FrmEntradas_Lotes},
  DefineComissao_Form in 'DefineComissao_Form.pas' {frmRedefineComissao},
  Agrupador_Form in 'Agrupador_Form.pas' {FrmAgrupador},
  Dados_Baixa_Receber_Multiplos_Form in 'Dados_Baixa_Receber_Multiplos_Form.pas' {FrmDadosBaixaReceberSelecao},
  ConfirmaEstorno_Form in 'ConfirmaEstorno_Form.pas' {FrmConfirmaEstorno},
  Entrada_Parcelamento_Form in 'Entrada_Parcelamento_Form.pas' {FrmEntradaParcelamento},
  AlteraPreco_Form in 'AlteraPreco_Form.pas' {frmAlteraPrecos},
  Filtra_AlteraPreco_Form in 'Filtra_AlteraPreco_Form.pas' {frmFiltraListaPreco},
  ContratosItens_Form in 'ContratosItens_Form.pas' {FrmContratosItens},
  Contratos_Form in 'Contratos_Form.pas' {FrmContratosClientesProdutos},
  Localizar_Contratos in 'Localizar_Contratos.pas' {FrmLocContratos},
  Leituras_Form in 'Leituras_Form.pas' {FrmLeituras},
  SelLeituras_Form in 'SelLeituras_Form.pas' {FrmSelLeituras},
  GerarLeituras_Form in 'GerarLeituras_Form.pas' {frmGerarLeituras},
  Defensivo_Form in 'Defensivo_Form.pas' {frmDefensivo},
  CategoriasDef_Form in 'CategoriasDef_Form.pas' {FrmCategoriasDef},
  ClassesToxicologicasDef_Form in 'ClassesToxicologicasDef_Form.pas' {FrmClassesToxicologicas},
  ClassAmbientalDef_Form in 'ClassAmbientalDef_Form.pas' {FrmClassAmbiental},
  ClassQuimicaDef_Form in 'ClassQuimicaDef_Form.pas' {FrmClassQuimica},
  FabricanteDef_Form in 'FabricanteDef_Form.pas' {FrmFabricantes},
  MatEmbalagemDef_Form in 'MatEmbalagemDef_Form.pas' {FrmMatEmbalagem},
  OrientacoesDef_Form in 'OrientacoesDef_Form.pas' {FrmOrientacoesDef},
  Registrante_Form in 'Registrante_Form.pas' {FrmRegistrantes},
  Localizar_Defensivo in 'Localizar_Defensivo.pas' {FrmLocDefensivos},
  Contratos_FRel2 in 'Contratos_FRel2.pas' {fRelContratos},
  Perfis_Form in 'Perfis_Form.pas' {FrmPerfis},
  Rotas_Form in 'Rotas_Form.pas' {FrmRotas},
  Estados_Form in 'Estados_Form.pas' {FrmEstados},
  Unidades_Conversao_Form in 'Unidades_Conversao_Form.pas' {FrmConversaoUnidades},
  PragasDef_Form in 'PragasDef_Form.pas' {FrmPragas},
  CulturasDef_Form in 'CulturasDef_Form.pas' {FrmCulturas},
  UndMedVazao_Form in 'UndMedVazao_Form.pas' {frmUndMedVazao},
  SelReceiturario_Form in 'SelReceiturario_Form.pas' {FrmSelReceituario},
  ListaDetFat_Form in 'ListaDetFat_Form.pas' {frmDetFat},
  Acerto_FRel in 'Acerto_FRel.pas' {FRelAcerto},
  FiltraMulti_Form in 'FiltraMulti_Form.pas' {frmFiltraMulti},
  Imp_Receita_Form in 'Imp_Receita_Form.pas' {frmImprimeReceita},
  ConfigFin_Form in 'ConfigFin_Form.pas' {FrmConfigFinanceira},
  ValoresOriginais_Form in 'ValoresOriginais_Form.pas' {FrmValoresOriginais},
  Act_Baixa_Form in 'Act_Baixa_Form.pas' {FrmAct_Baixa},
  Act_Contas_Form in 'Act_Contas_Form.pas' {frmAct_Contas},
  Act_Renegociacao_Form in 'Act_Renegociacao_Form.pas' {FrmAct_Renegociacao},
  Localizar_ProdutoPdv in 'Localizar_ProdutoPdv.pas' {FrmLocProdutoPdv},
  DefineComissaoItem_Form in 'DefineComissaoItem_Form.pas' {frmDefineComissaoItem},
  SelComissoes_Form in 'SelComissoes_Form.pas' {FrmSelComissoes},
  Cm2_GeraFinanceiro in 'Cm2_GeraFinanceiro.pas' {frmGeraFinComissoes},
  ComissoesTerceiros_FRel in 'ComissoesTerceiros_FRel.pas' {FRelComissoesTerceiros},
  Exporta_Iagro_Form in 'Exporta_Iagro_Form.pas' {FrmExportaIagro},
  EventoContabil_Form in 'EventoContabil_Form.pas' {FrmEventoContabil},
  Cheque_Acerto_Form in 'Cheque_Acerto_Form.pas' {FrmCheque_Acerto},
  Mov_Banc_Acerto_Form in 'Mov_Banc_Acerto_Form.pas' {FrmMovAvisoBancario},
  SincronizaCadastros_Form in 'SincronizaCadastros_Form.pas' {frmSincronizaCadastros},
  TabelaPreco_Form in 'TabelaPreco_Form.pas' {FrmTabelaPreco},
  Filtra_TabelaPreco_Form in 'Filtra_TabelaPreco_Form.pas' {frmFiltraTabelaPreco},
  VendedorTabela_Form in 'VendedorTabela_Form.pas' {frmTabelaVendedor},
  Romaneios_Form in 'Romaneios_Form.pas' {FrmRomaneios},
  Estorna_Acerto_Form in 'Estorna_Acerto_Form.pas' {frmEstornaAcerto},
  Act_Filtro_Parceiro in 'Act_Filtro_Parceiro.pas' {FrmFiltraParceiro},
  FluxoCaixa_Form in 'FluxoCaixa_Form.pas' {frmFluxoCaixa},
  Flx_ReceberPrevista in 'Flx_ReceberPrevista.pas' {FrmFlxReceberPrevista},
  Ordens_Servicos_Horas_Form in 'Ordens_Servicos_Horas_Form.pas' {FrmOrdens_Servicos_Horas},
  SelMensalidades_Form in 'SelMensalidades_Form.pas' {FrmSelMensalidades},
  GerarMensalidades_Form in 'GerarMensalidades_Form.pas' {frmGerarMensalidades},
  Mensalidades_Form in 'Mensalidades_Form.pas' {frmMensalidade},
  GerarFaturamentos_Form in 'GerarFaturamentos_Form.pas' {frmGerarFaturamentos},
  Ordens_Servicos_Email_Form in 'Ordens_Servicos_Email_Form.pas' {FrmOrdens_Servicos_Email},
  EviaEmail_Thread in 'EviaEmail_Thread.pas',
  ConsultaRomaneioEntrega_Form in 'ConsultaRomaneioEntrega_Form.pas' {FrmConsultaRomaneio},
  Filtro_Parceiro_Email in 'Filtro_Parceiro_Email.pas' {FrmFiltraParceiroEmail},
  Rel_ResumoAtendimento in 'Rel_ResumoAtendimento.pas' {FRel_ResumoAtendimentos},
  IndicesPdv_Form in 'IndicesPdv_Form.pas' {Pdv_FormIndices},
  NFeStatus_Form in 'NFeStatus_Form.pas' {frmStatus},
  TipoMovimento_Form in 'TipoMovimento_Form.pas' {frmTipoMovimento},
  Filtro_Vendedor_Romaneio in 'Filtro_Vendedor_Romaneio.pas' {FrmFiltraVendedorRomaneio},
  Contatos_Form in 'Contatos_Form.pas' {FrmContatos},
  BIEstoqueGrade_Form in 'BIEstoqueGrade_Form.pas' {FrmBIEstoqueGrade},
  TipoEndereco_Form in 'TipoEndereco_Form.pas' {FrmTipoEndereco},
  Filtra_Baixa_Pagar_Form in 'Filtra_Baixa_Pagar_Form.pas' {FrmBaixaContasPagar},
  Gravidade_Form in 'Gravidade_Form.pas' {FrmGravidade},
  Folha_Form in 'Folha_Form.pas' {FrmFolha},
  Tipo_MovtoFolha_Form in 'Tipo_MovtoFolha_Form.pas' {frmTipoMovimentoFolha},
  Filtra_Folha_Form in 'Filtra_Folha_Form.pas' {FrmFiltraFolha},
  Comandas_Form in 'Comandas_Form.pas' {frmComandas},
  HelpReducao_Form in 'HelpReducao_Form.pas' {frmHelpReducaoZ},
  ContratosGrupo_Form in 'ContratosGrupo_Form.pas' {FrmContratosGrupos},
  Localizar_Contratos_Copias in 'Localizar_Contratos_Copias.pas' {FrmLocContratosCopias},
  Localizacao_Est_Form in 'Localizacao_Est_Form.pas' {FrmLocalizacao},
  Padrao_FRel in 'Padrao_FRel.pas' {FRelPadrao},
  EstoqueMaxMin_FRel2 in 'EstoqueMaxMin_FRel2.pas' {FRelEstoqueMaxMin2},
  PosicaoEstoqueGrafico_FRel in 'PosicaoEstoqueGrafico_FRel.pas' {fRelPosicaoEstoqueGrafico},
  Gera_Geolocalizacao_Form in 'Gera_Geolocalizacao_Form.pas' {frmGerarGeolocalizacao},
  uXMLNodes in 'uXMLNodes.pas',
  uGeoCode in 'uGeoCode.pas',
  Mapa_Form in 'Mapa_Form.pas' {frmMapa},
  WizardXML_Form in 'WizardXML_Form.pas' {frmImportaNFe},
  ACBrHTMLtoXML in 'ACBrHTMLtoXML.pas',
  GIFImage in 'GifImage.pas',
  ClienteCidades_FRel in 'ClienteCidades_FRel.pas' {fRelClientesCidade},
  Bairros_Form in 'Bairros_Form.pas' {FrmBairros},
  Representante_Form in 'Representante_Form.pas' {FrmRepresentantes},
  ContratosConstru_Form in 'ContratosConstru_Form.pas' {FrmContratoConstru},
  Localizar_Contratos_Obras in 'Localizar_Contratos_Obras.pas' {FrmLocContratosObras},
  Rel_ContratoObra in 'Rel_ContratoObra.pas' {FRel_ContratoObra},
  Gerar_FatSaida in 'Gerar_FatSaida.pas' {FrmGeraFatSaida},
  untCadPadrao in 'untCadPadrao.pas' {frmCadPadrao},
  untCadLogradouro in 'untCadLogradouro.pas' {frmCadLogradouro},
  untCadBairros in 'untCadBairros.pas' {frmCadBairros},
  untCadCidades in 'untCadCidades.pas' {frmCadCidades},
  untCadEstados in 'untCadEstados.pas' {frmCadEstados},
  untCadPaises in 'untCadPaises.pas' {frmCadPaises},
  untCadMoedas in 'untCadMoedas.pas' {frmCadMoedas},
  untCadPessoas in 'untCadPessoas.pas' {frmCadPessoas},
  untCadAtividades in 'untCadAtividades.pas' {frmCadAtividades},
  untCadRegioes in 'untCadRegioes.pas' {frmCadRegiao},
  untCadPadraoMaster in 'untCadPadraoMaster.pas' {frmCadPadraoMaster},
  untCadVendedor2 in 'untCadVendedor2.pas' {frmCadVendedor2},
  untMainPadrao in 'untMainPadrao.pas' {frmManutencaoPadrao},
  untCadContasPagar in 'untCadContasPagar.pas' {frmCadContasPagar},
  UntCadCategoriaClientes in 'UntCadCategoriaClientes.pas' {FrmCadCategoriaClientes},
  UntCadCobradores in 'UntCadCobradores.pas' {FrmCadCobradores},
  UntCadTerceiros in 'UntCadTerceiros.pas' {FrmCadTerceiro},
  UntCadTecnicos in 'UntCadTecnicos.pas' {frmCadTecnicos},
  UntCadUsuarios in 'UntCadUsuarios.pas' {frmCadUsuarios},
  untCadUnidadesMedidas in 'untCadUnidadesMedidas.pas' {frmCadUnidadesMedidas},
  UntCadMarcas in 'UntCadMarcas.pas' {frmCadMarcas},
  UntCadModelo in 'UntCadModelo.pas' {frmCadModelo},
  UntCadSecoesProdutos in 'UntCadSecoesProdutos.pas' {frmCadSecoesProdutos},
  UntCadLocalizacaoEstoque in 'UntCadLocalizacaoEstoque.pas' {frmCadLocalizacaoEstoque},
  UntCadCor in 'UntCadCor.pas' {frmCadCor},
  UntCadMaterial in 'UntCadMaterial.pas' {frmCadMaterial},
  UntCadAplicacaoProduto in 'UntCadAplicacaoProduto.pas' {frmCadAplicacaoProduto},
  UntCadBancos in 'UntCadBancos.pas' {frmCadBancos},
  UntCadMotivosDevolucao in 'UntCadMotivosDevolucao.pas' {frmCadMotivosDevolucao},
  UntCadContaCorrente in 'UntCadContaCorrente.pas' {frmCadContaCorrente},
  UntCadAdministradoras in 'UntCadAdministradoras.pas' {frmCadAdministradoras},
  UntCadLocalCobranca in 'UntCadLocalCobranca.pas' {frmCadLocalCobranca},
  UntCadTipoDocumento in 'UntCadTipoDocumento.pas' {frmCadTipoDocumento},
  UntCadCotacoes in 'UntCadCotacoes.pas' {frmCadCotacoes},
  UntCadAlegacao in 'UntCadAlegacao.pas' {frmCadAlegacao},
  UntCadEventoContabil in 'UntCadEventoContabil.pas' {frmCadEventoContabil},
  UntCadStatusServico in 'UntCadStatusServico.pas' {frmCadStatusServico},
  UntCadDefeitos in 'UntCadDefeitos.pas' {frmCadDefeitos},
  UntCadServicoExecutado in 'UntCadServicoExecutado.pas' {frmCadServicoExecutado},
  UntCadProblemaIdentificado in 'UntCadProblemaIdentificado.pas' {frmCadMotivoChamado},
  UntCadTipoContrato in 'UntCadTipoContrato.pas' {frmCadTipoContrato},
  untCadFornecedores in 'untCadFornecedores.pas' {frmCadFornecedores},
  untCadClientes in 'untCadClientes.pas' {frmCadClientes},
  untFormPadrao in 'untFormPadrao.pas' {FormPadrao},
  untCadOS in 'untCadOS.pas' {frmCadOS},
  untCadContratoAtendimento in 'untCadContratoAtendimento.pas' {frmCadContratoAtendimento},
  UntCadClassificacao in 'UntCadClassificacao.pas' {frmCadClassificacao},
  untCadTipoVeitulo in 'untCadTipoVeitulo.pas' {frmCadTipoVeiculo},
  untCadMarcaVeiculo in 'untCadMarcaVeiculo.pas' {frmCadMarcaVeiculo},
  UntCadTipoMovimento in 'UntCadTipoMovimento.pas' {frmCadTipoMovimento},
  untCadProdutos in 'untCadProdutos.pas' {frmCadProdutos},
  UntCadContratoCopias in 'UntCadContratoCopias.pas' {frmCadContratoCopias},
  UntCadGrupos in 'UntCadGrupos.pas' {FrmCadGrupos};

{$R *.RES}

var
  ExtendedStyle : Integer;
begin
  Application.Initialize;
  Application.Title := 'HelpStore v 1.0';
  Application.CreateForm(TDmApp, DmApp);
  Application.CreateForm(TDMProcs, DMProcs);
  Application.CreateForm(TDMProcs2, DMProcs2);
  Application.CreateForm(TDMProcs3, DMProcs3);
  Application.CreateForm(TDMVendas, DMVendas);
  Application.CreateForm(TDmVendas2, DmVendas2);
  Application.CreateForm(TDMCadastros, DMCadastros);
  Application.CreateForm(TDMEstoque, DMEstoque);
  Application.CreateForm(TDMMensagem, DMMensagem);
  Application.CreateForm(TDmFinanceiro, DmFinanceiro);
  Application.CreateForm(TdmFinanceiro2, dmFinanceiro2);
  Application.CreateForm(TDMRelatorios, DMRelatorios);
  Application.CreateForm(TdmRelatorios2, dmRelatorios2);
  Application.CreateForm(TdmCadastros2, dmCadastros2);
  Application.CreateForm(TDmServicos, DmServicos);
  Application.CreateForm(TDmOrdemCarga, DmOrdemCarga);
  Application.CreateForm(TDmSerie_Customizaveis, DmSerie_Customizaveis);
  Application.CreateForm(TFrmMain, FrmMain);
  Application.Run;
end.
